apiVersion: v1
kind: Pod
metadata:
  name: citrus-sample-todo-tests
spec:
  restartPolicy: Never
  containers:
  - name: citrus-sample-todo-tests
    image: citrus/todo-app-tests:2.7.1-SNAPSHOT
    imagePullPolicy: Never
    securityContext:
      privileged: false